# To use this file, rename to app.yaml and remove the appengine-web.xml file
runtime: custom
env: flex

manual_scaling:
  instances: 2

env_variables:
  JETTY_ARGS: -Djava.util.logging.config.file=WEB-INF/logging.properties
  JETTY_MODULES_ENABLE: gcp-datastore-sessions

handlers:
  - url: /.*
    script: this field is required, but ignored
